### ISSUE TITLE
A sentence containing '\n' is yanked twice in setting clipboard+=unnamed

### ISSUE THREAD

**Issue by mitsu0525** [Shougo/neoyank.vim#17] opened 2018-11-07 06:42 UTC
Hi @Shougo,

When I yank a sentence containing '\n' (i.e. press 'dd', 'yy'), yank history has the sentence and '\n' added at its tail like

```
*: on_source = ['denite.nvim']\n
*: on_source = ['denite.nvim']
```

I think that neoyank adds a last yanked sentence from clipboard when I open neoyank with denite.
If I don't use * register, this problem doesn't occur.

**Comment by Shougo** [comment] 2018-11-07 07:08
I don't reproduce the error.
Please provide the minimal init.vim with the reproduce-able instruction.
If not, I will close the issue.
Because it works for me.

**Comment by mitsu0525** [comment] 2018-11-07 07:57
I can reproduce the error with the .vimrc
```
" reset augroup
augroup MyAutoCmd
  autocmd!
augroup END

" dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

let s:dein_path = expand('~/.vim/dein')
let s:dein_repo_path = s:dein_path . '/repos/github.com/Shougo/dein.vim'

" dein.vim がなければ github からclone
if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_path)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_path
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_path, ':p')
endif

if dein#load_state(s:dein_path)
  call dein#begin(s:dein_path)

  let g:config_dir  = expand('~/.vim/rc')
  let s:toml        = g:config_dir . '/dein.toml'
  let s:lazy_toml   = g:config_dir . '/dein_lazy.toml'

  " TOML 読み込み
  call dein#load_toml(s:toml,      {'lazy': 0})
  call dein#load_toml(s:lazy_toml, {'lazy': 1})

  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
"End dein Scripts-------------------------

set encoding=utf-8
scriptencoding utf-8
set fileencoding=utf-8
set fileencodings=ucs-boms,utf-8,euc-jp,cp932
set fileformats=unix,dos,mac
set clipboard& clipboard+=unnamed
```
and dein.toml is
```
[[plugins]]
repo = 'Shougo/dein.vim'
```
dein_lazy.toml is
```
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']
 
[[plugins]]
repo = 'Shougo/denite.nvim'
on_if = 'has("python3")'
on_cmd = 'Denite'
```

**Comment by mitsu0525** [comment] 2018-11-07 08:04
For example, if I yank first line of .vimrc `" reset augroup`  with `dd`,
`:Denite neoyank` provides
```
*: " reset augroup\n
*: " reset augroup
```

I use vim8
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 14 2018 21:57:14)
macOS version
Included patches: 1-450
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1 -lobjc
```

**Comment by Shougo** [comment] 2018-11-07 08:51
I have tested it with minimal vimrc and I cannot reproduced.
neoyank displays newlines as backslash n character.
Closing.

**Comment by Shougo** [comment] 2018-11-07 08:52
The backslash is displayed, but it is not twice.

**Closed as completed** 2018-11-07 08:52 UTC

**Comment by Shougo** [comment] 2018-11-07 08:54
neoyank is open source project.
You can investigate more.
